name = "UniAdminTools"
uuid = "8ce952d8-4570-4d9b-a191-c4e6a1af656b"
authors = ["MilesCranmer <miles.cranmer@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
